apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "slingshot-operator.fullname" . }}-manager
  labels:
    {{- include "slingshot-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "slingshot-operator.fullname" . }}-manager
subjects:
- kind: ServiceAccount
  name: {{ include "slingshot-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
