{{- if .Values.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "slingshot-operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slingshot-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "slingshot-operator.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "slingshot-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
