{{- if or .Values.webhook.cxidriver.enabled .Values.webhook.sidecar.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slingshot-operator.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slingshot-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: {{ .Values.webhook.port }}
      protocol: TCP
      name: https
  selector:
    {{- include "slingshot-operator.selectorLabels" . | nindent 4 }}
{{- end }}
